services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-oc-api
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql_network

  mysql:
    image: mysql:8.0
    container_name: mysql-kelompok1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-kelompok1}
      MYSQL_USER: ${MYSQL_USER:-kelompok1}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-kelompok1}
      MYSQL_DATABASE: classicmodels
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kelompok1", "-p${MYSQL_PASSWORD:-kelompok1}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mysql_network:
    driver: bridge
